# -*- coding: utf-8 -*-
"""script_send_message_telegram_automatic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w6t1dAkElxKDPh2CzcgMfIMLhHYUgMCi
"""

pip install telethon

pip install nest_asyncio

from IPython.display import display, Javascript

def run_js_code(js_code):
    display(Javascript(js_code))

# Kode JavaScript Anda
js_code = """
function ClickConnect(){
    console.log("Clicked on connect button to prevent timeout.");
    document.querySelector("colab-toolbar-button#connect").click()
}
setInterval(ClickConnect, 60000);
"""

run_js_code(js_code)

from telethon import TelegramClient
import nest_asyncio
import asyncio

# Apply nest_asyncio to avoid asyncio loop issues
nest_asyncio.apply()

# Replace with your API ID and API Hash
api_id = '24079184'
api_hash = '142e695f7431af05c582f8610329f1ca'

# Initialize the Telegram Client
client = TelegramClient('new_session2_name', api_id, api_hash)

# List of messages to send
messages = [
    '/report_atm_kc 0245',
    '/report_crm_kc 0245'
]

async def send_message():
    # Connect to Telegram
    await client.start()

    chat = '@jaguargesit_bot'  # Replace with your target channel ID or username

    # Infinite loop to continuously send messages
    while True:
        for message in messages:
            await client.send_message(chat, message)

        # Wait for 1 minute before sending the messages again
        await asyncio.sleep(600)

    # Note: No need to disconnect since the loop is infinite

# Run the asynchronous function
asyncio.run(send_message())

